### ISSUE TITLE
AWS cloud failed to find ClusterID

### ISSUE THREAD

**Issue by nipeharefa** [david-igou/k3s-aws-ansible#1]
I got some error on pod aws-controller, any suggest may how to fix?

Thank you.

```
I0104 09:51:31.916281       1 serving.go:319] Generated self-signed cert in-memory
W0104 09:51:32.367991       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0104 09:51:32.370424       1 controllermanager.go:117] Version: v0.0.0-master+$Format:%h$
W0104 09:51:32.370563       1 plugins.go:118] WARNING: aws built-in cloud provider is now deprecated. The AWS provider is deprecated and will be removed in a future release
I0104 09:51:32.370749       1 aws.go:1183] Building AWS cloudprovider
I0104 09:51:32.370874       1 aws.go:1149] Zone not specified in configuration file; querying AWS metadata service
E0104 09:51:32.618676       1 tags.go:95] Tag "KubernetesCluster" nor "kubernetes.io/cluster/..." not found; Kubernetes may behave unexpectedly.
F0104 09:51:32.618871       1 controllermanager.go:121] Cloud provider could not be initialized: could not init cloud provider "aws": AWS cloud failed to find ClusterID
```

**Comment by david-igou** [comment]
@nipeharefa The controller looks for a label/tag on aws objects (ec2 dashboard -> select instance -> add/edit tags) with `key:  kubernetes.io/cluster/<clusterid>` (clusterid is "default" by default) and `value: owned`

So, your ec2 instances which are your nodes probably need that tag.

Additionally, this repo has been unmaintained for over a year. So if you used the image referenced in `manifests/aws-cloud-controller-manager.yml` - it is a 14 month old image and could be failing for other reasons if anything changed with the aws api in the past year. I built my own because at the time there was no public builds/manifests from the maintainers. This has changed since, I recommend you use their manifests: https://github.com/kubernetes/cloud-provider-aws/blob/master/manifests/aws-cloud-controller-manager-daemonset.yaml

**Comment by nipeharefa** [comment]
Okay @David-Igou, I have forgotten to add tag.
Thank you 👍
